version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
      - mkdir dist
  build:
    commands:
      - git checkout-index -a -f --prefix=./dist/
  post_build:
    commands:
artifacts:
  files:
    - dist/
  discard-paths: yes