version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
      - mkdir dist
  build:
    commands:
      - git checkout-index -a -f --prefix=./dist/
      - rm dist/buildspec.yml
  post_build:
    commands:
      - ls -lhat
artifacts:
  files:
    - ./**/*
  discard-paths: no
  base-directory: dist/